#!/usr/bin/python3
# ----- imports -----
import gi

gi.require_version('Gtk', '3.0')
# noinspection PyUnresolvedReferences
from gi.repository import Gtk as gtk
# noinspection PyUnresolvedReferences
from gi.repository import Gdk as gdk

gi.require_version('GtkSource', '3.0')
# noinspection PyUnresolvedReferences
from gi.repository import GtkSource as gtksource
# noinspection PyUnresolvedReferences
from gi.repository import Pango as pango

from editor_class import Editor
from windows import *

# -------------------

VERSION = "1.0.1"


class MainWindow(BuildMainWindow):
	"""Instance of application (main window)"""

	def __init__(self):
		super().__init__()
		self.editors = []

		self.new_editor()

		# self.window.
		self.window.resize(800, 600)
		self.window.show_all()
		gtk.main()

	def new_editor(self, load=False):
		ed = Editor(self.notebook)
		if load:
			ed.loadfile()
		self.editors.append(ed)
		self.notebook.append_page(ed.view, gtk.Label(label=ed.filename))


if __name__ == "__main__":
	MainWindow()
