#!/usr/bin/python3
# ----- imports -----
import gi

gi.require_version('Gtk', '3.0')
# noinspection PyUnresolvedReferences
from gi.repository import Gtk as gtk
# noinspection PyUnresolvedReferences
from gi.repository import Gdk as gdk

gi.require_version('GtkSource', '3.0')
# noinspection PyUnresolvedReferences
from gi.repository import GtkSource as gtksource
# noinspection PyUnresolvedReferences
from gi.repository import Pango as pango

from windows import *

# -------------------

VERSION = "1.0.1"


class Editor(BuildEditor):

	def __init__(self):
		super().__init__()
		gtk.main()


if __name__ == "__main__":
	Editor()