#!/usr/bin/python3
VERSION=1.0.1

from lex import *
from emit import *
from parse import *
import sys, argparse, os, tempfile

def main(file, output, compiler, verbose):
    if verbose:
        print("AttempLang Compiler")
    
    temp = tempfile.NamedTemporaryFile(suffix=".c", mode="w+t")

    with open(file, 'r') as inputFile:
        input = inputFile.read()

    # Initialize the lexer, emitter, and parser.
    lexer = Lexer(input)
    emitter = Emitter(temp)
    parser = Parser(lexer, emitter)

    if verbose:
        print("Parsing file.")
    parser.program() # Start the parser.
    emitter.writeFile() # Write the output to file.
    if verbose:
        print("Parsing complete.")

        print("Compiling file.") 
    # make sure dirs exist
    if not os.path.exists(os.path.dirname(output)):
        os.mkdir(os.path.dirname(output))
    # compile
    os.system(f"{compiler} {temp.name} -o {output}")
    temp.close()
    if verbose:
        print("Compiling completed.")
    
if __name__ == '__main__':
    
    if '--version' in sys.argv:

        path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'version.txt')
        with open(path, 'r') as f:
            version = f.read()
        print(f"AttemptLang compiler version {version} by Sjoerd Vermeulen")
        sys.exit(0)

    parser = argparse.ArgumentParser('attemptcomp', description='AttemptLang compiler',
                 usage='%(prog)s [-v] input [-o/--output file]\n -h/--help: show help message')
    parser.add_argument('input', type=str, help='input script (program passed in as .Al file)')
    parser.add_argument('-o', '--output', dest='file', action='store', help='specify the output file')
    parser.add_argument('-c', '--compiler', dest='compiler', default='/usr/bin/gcc', action='store', help='specify the c compiler (gcc by default)')
    parser.add_argument('-v', '--verbose', action='store_true', default=0, help='verbose compiling')
    parser.add_argument('--version', action='store_true', help='print version info')

    args = parser.parse_args()
    
    # check args n stuff
    if not os.path.exists(args.input):
        print(f"Error: File '{args.input}' does not exist")
        sys.exit(1)
    if not args.input.endswith('.Al'):
        print(f"Error: File '{args.input}' is no .Al file")
        sys.exit(1)
        
    if args.file == None:
        outfile = os.path.join(os.getcwd(), "bin", os.path.splitext(os.path.basename(args.input))[0])
    else:
        outfile = args.file
        if not os.path.exists(os.path.dirname(outfile)):
            print(f"Error: Output directory '{os.path.dirname(outfile)}' does not exist")
            sys.exit(1)
    
    if not os.path.exists(args.compiler):
        print(f"Error: Compiler '{args.compiler}' not found")
        sys.exit(1)
    
    main(args.input, outfile, args.compiler, args.verbose)